// Transparent ridge-regression fitting utility for real calibration datasets.
// No synthetic accuracy claims are generated by this script.
import { readFile, writeFile } from 'node:fs/promises';
import { basename } from 'node:path';

const CHANNELS=['f1','f2','f3','f4','f5','f6','f7','f8','clear','nir'];
function parseCsv(text){
  const lines=text.trim().split(/\r?\n/).filter(Boolean); const head=lines[0].split(',').map(x=>x.trim());
  return lines.slice(1).map(line=>{const cells=line.split(',');return Object.fromEntries(head.map((h,i)=>[h,cells[i]?.trim()??'']));});
}
function transpose(A){return A[0].map((_,i)=>A.map(r=>r[i]));}
function matMul(A,B){return A.map(r=>B[0].map((_,j)=>r.reduce((s,v,k)=>s+v*B[k][j],0)));}
function inverse(A){
  const n=A.length, M=A.map((r,i)=>[...r,...Array.from({length:n},(_,j)=>i===j?1:0)]);
  for(let i=0;i<n;i++){
    let p=i;for(let r=i+1;r<n;r++)if(Math.abs(M[r][i])>Math.abs(M[p][i]))p=r;[M[i],M[p]]=[M[p],M[i]];
    if(Math.abs(M[i][i])<1e-12)throw new Error('singular calibration matrix');
    const d=M[i][i];M[i]=M[i].map(v=>v/d);
    for(let r=0;r<n;r++)if(r!==i){const f=M[r][i];M[r]=M[r].map((v,c)=>v-f*M[i][c]);}
  }
  return M.map(r=>r.slice(n));
}
function fit(rows,target,lambda=1e-6){
  const X=rows.map(r=>[1,...CHANNELS.map(c=>Number(r[c]))]); const y=rows.map(r=>[Number(r[target])]);
  const Xt=transpose(X); const XtX=matMul(Xt,X); for(let i=1;i<XtX.length;i++)XtX[i][i]+=lambda;
  const beta=matMul(inverse(XtX),matMul(Xt,y)).map(r=>r[0]); return beta;
}
function predict(beta,row){return beta[0]+CHANNELS.reduce((s,c,i)=>s+beta[i+1]*Number(row[c]),0);}
function metrics(beta,rows,target){const errs=rows.map(r=>predict(beta,r)-Number(r[target]));return {n:rows.length,mae:errs.reduce((s,e)=>s+Math.abs(e),0)/errs.length,rmse:Math.sqrt(errs.reduce((s,e)=>s+e*e,0)/errs.length),bias:errs.reduce((s,e)=>s+e,0)/errs.length};}

const input=process.argv[2], output=process.argv[3]||'calibration-profile.json';
if(!input){console.error('Usage: node calibration/fit_profile.mjs dataset.csv [output.json]');process.exit(2);}
const rows=parseCsv(await readFile(input,'utf8'));
if(rows.length<12)throw new Error('Need at least 12 real reference rows; more and more diverse data is strongly recommended.');
const sources=[...new Set(rows.map(r=>r.source_id||r.source||'unknown'))];
const heldSource=sources.length>1?sources.at(-1):null;
const train=heldSource?rows.filter(r=>(r.source_id||r.source||'unknown')!==heldSource):rows.filter((_,i)=>i%5!==0);
const test=heldSource?rows.filter(r=>(r.source_id||r.source||'unknown')===heldSource):rows.filter((_,i)=>i%5===0);
const lux=fit(train,'reference_lux'), mel=fit(train,'reference_melanopic_edi');
const profile={
  generatedAt:new Date().toISOString(), sourceFile:basename(input), status:'requires engineering review before product use', channels:CHANNELS,
  intercepts:{lux:lux[0],melanopicEdi:mel[0]},
  coefficients:{lux:Object.fromEntries(CHANNELS.map((c,i)=>[c,lux[i+1]])),melanopicEdi:Object.fromEntries(CHANNELS.map((c,i)=>[c,mel[i+1]]))},
  heldOut:{strategy:heldSource?`source_id=${heldSource}`:'every fifth row',lux:metrics(lux,test,'reference_lux'),melanopicEdi:metrics(mel,test,'reference_melanopic_edi')}
};
await writeFile(output,JSON.stringify(profile,null,2));console.log(JSON.stringify(profile.heldOut,null,2));
